services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    networks:
      - microstaff-network


  company-service:
    build:
      context: ./company-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8082"
    depends_on:
      - user-service
    networks:
      - microstaff-network

networks:
  microstaff-network:
    driver: bridge


