spring:
  application:
    name: api-gateway
server:
  port: 8080

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/api/company/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka